DELETE http://localhost:3003/api/blogs/689ec4980dcb80e6c0788ee3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMSIsImlkIjoiNjg5NDc3NjcwMjEyYmI2ZmM3ZGFiNWExIiwiaWF0IjoxNzU1MjM0NzMzfQ.cKavM_nFo0sE6JP1AnM2c3k72EvdCCpZtuJCr5KTQCo